scratch: "/tsl/scratch/macleand/nlrsnake/"
sample_fasta_file: "/hpc-home/macleand/samples_to_fasta.csv"
seqs_per_file: 6000
species: "Arabidopsis_thaliana"
helixer_options: "--overlap-offset 53460 --overlap-core-length 80190 --no-multiprocess"
